#!/bin/bash

S1="DNT/ETH,OAX/ETH,HSR/BTC,ETH/BTC,EOS/ETH,GAS/BTC,BNT/ETH,WTC/BTC,SNT/ETH,BNB/ETH,BTC/USDT,LRC/BTC,BNB/BTC,ICN/ETH,YOYOW/BTC,ZRX/BTC"
S2="OMG/ETH,QTUM/ETH,QTUM/BTC,LRC/ETH,STRAT/ETH,SNM/ETH,ZRX/ETH,NEO/ETH,IOTA/BTC,FUN/ETH,SNGLS/ETH,OMG/BTC,BCH/BTC,BQX/ETH,STRAT/BTC,GRS/BTC"
S3="MTL/ETH,MDA/ETH,MDA/BTC,ETC/BTC,LINK/ETH,IOTA/ETH,SUB/ETH,ZEC/BTC,XVG/ETH,BNT/BTC,EOS/BTC,SUB/BTC,ICN/BTC,DASH/BTC,EVX/BTC,SALT/ETH"
S4="ENG/ETH,REQ/BTC,HSR/ETH,TRX/BTC,REQ/ETH,AST/ETH,TRX/ETH,BTG/BTC,ENJ/BTC,ARK/BTC,EVX/ETH,XRP/BTC,VIB/BTC,POWR/BTC,NULS/BNB,STORJ/BTC"
S5="RDN/ETH,XMR/ETH,BCPT/BTC,BCPT/BNB,QSP/BNB,BTS/BTC,BAT/ETH,CDT/ETH,CDT/BTC,LSK/BNB,BTS/ETH,LSK/BTC,BCD/BTC,FUEL/ETH,TNT/ETH,DGD/ETH,SYS/BNB"
S6="ADX/ETH,XLM/BTC,IOTA/BNB,LEND/BTC,DGD/BTC,XLM/ETH,LTC/ETH,CMT/ETH,CMT/BTC,CND/BTC,WAVES/ETH,WABI/ETH,ICX/BTC,TNB/BTC,LTC/USDT,WAVES/BNB"
S7="ELF/ETH,WAVES/BTC,NEBL/BTC,OST/BTC,EDO/BTC,BRD/ETH,TRIG/BTC,EDO/ETH,NAV/BTC,INS/BTC,APPC/BTC,STEEM/ETH,XRB/BNB,STEEM/BTC,PIVX/BNB,STEEM/BNB"
S8="BLZ/BNB,AE/BNB,ZIL/BNB,NCASH/BTC,NCASH/ETH,ZIL/ETH,RPX/BTC,RPX/ETH,RPX/BNB,XEM/BNB,ZIL/BTC,ADA/BNB,SYS/ETH,BCN/BTC,CLOAK/BTC,CLOAK/ETH,XRP/USDT"

nohup ./bulk-lambda-multiprocess-run.sh 1 $S1 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 2 $S2 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 3 $S3 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 4 $S4 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 5 $S5 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 6 $S6 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 7 $S7 >> system-launcher.log 2>1 &
nohup ./bulk-lambda-multiprocess-run.sh 8 $S8 >> system-launcher.log 2>1 &